services:
  - type: web
    name: line-webhook
    env: python
    region: oregon
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "pip install -r requirements.txt"
    repo: https://github.com/kimchinam09/line-webhook
    plan: free
   

