services:
  - type: web
    name: line-webhook
    env: python
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: "python app.py"
    repo: https://github.com/kimchinam09/line-webhook
    plan: free

